#!/bin/bash

if [ -z "$1" ]; then
	echo "Fetching latest dump from production..."
	ssh coinflipper.org cat "~/backups/subcontest/subcontest.dump" | \
		docker exec -i subcontest-mongo mongorestore --drop --archive
else
	echo "Restoring from $1..."
	docker exec -i subcontest-mongo mongorestore --drop --archive < "$1"
fi
